# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
rule_files:
    - 'alert.rules'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - prometheus-alertmanager:9093
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['prometheus:9090']
    - job_name: 'prometheus-node-exporter'
      static_configs:
        - targets: ['prometheus-node-exporter:9100']
    - job_name: 'nginx-vts-exporter:'
      static_configs:
        - targets: ['nginx-vts-exporter:9913']
