version: '3.5'

networks:
  frontend:
    name: frontend
  backend:
    name: backend
  default:
    name: frontend

volumes:
  nextcloud-db:
    driver: local
  nextcloud-redis:
    driver: local
  nextcloud-html:
    driver: local
  nginx-conf:
    driver: local
  nginx-logs:
    driver: local
  nginx-certs:
    driver: local
  nginx-html:
    driver: local
  portainer-data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local


services:

  nextcloud-db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    networks:
      - backend
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - TZ=${DOCKER_TZ}
      - MYSQL_ROOT_PASSWORD=${NEXCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}

  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always
    environment:
      - TZ=${DOCKER_TZ}
    sysctls:
      net.core.somaxconn: 511
      # see readme.md
    networks:
      - backend
    volumes:
      - nextcloud-redis:/var/lib/redis

  nextcloud-app:
    container_name: nextcloud-app
    build: ./nextcloud/.
    #image: local.repo.com/nextcloud:latest
    networks:
      - backend
    restart: always
    depends_on:
      - nextcloud-db
    environment:
      - TZ=${DOCKER_TZ}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PORT=6379
    volumes:
      - nextcloud-html:/var/www/html
      - ${MY_DOCKER_DATA_DIR}/nextcloud/data:/var/www/html/data

  nextcloud-web:
    container_name: nextcloud-web
    build: ./nginx-fpm/.
    #image: local.repo.com/nginx-fpm:latest
    networks:
      backend:
      frontend:
        aliases:
          - nextcloud-vts-status
    restart: always
    depends_on:
      - nextcloud-app
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${NEXTCLOUD_DOMAIN}
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${NEXTCLOUD_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    volumes:
      - nextcloud-html:/var/www/html:ro
      - ${MY_DOCKER_DATA_DIR}/nextcloud/data:/var/www/html/data:ro

  simple-apache-php:
    container_name: simple-apache-php
    build: ./simple-apache-php/.
    #image: local.repo.com/simple-apache-php:latest
    restart: always
    expose:
      - "80"
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${SIMPLE_APACHE_PHP_DOMAIN}
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${SIMPLE_APACHE_PHP_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${SIMPLE_APACHE_PHP_DOMAIN}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - frontend
    volumes:
      - ${MY_DOCKER_DATA_DIR}/simple-apache-php/src:/var/www/html


  nginx-redirect:
    container_name: nginx-redirect
    image: nginx:latest
    restart: always
    expose:
      - "80"
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${REDIRECT_DOMAINS}
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${REDIRECT_DOMAINS}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    networks:
      - frontend
    volumes:
      - ${MY_DOCKER_DATA_DIR}/nginx-redirect/conf.d:/etc/nginx/conf.d

  grav:
    container_name: grav
    build: ./grav/.
    #image: local.repo.com/grav:latest
    restart: always
    expose:
      - "80"
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${GRAV_DOMAIN}
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${GRAV_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    networks:
      - frontend
    volumes:
      - ${MY_DOCKER_DATA_DIR}/grav:/var/www/html:cached
      - ${MY_DOCKER_DATA_DIR}/path-to-favicon.png:/var/www/html/user/themes/quark/images/favicon.png
      - ${MY_DOCKER_DATA_DIR}/path-to-logo.svg:/var/www/html/user/themes/quark/images/grav-logo.svg

  nginx:
    container_name: nginx
    build: ./nginx-vts/.
    #image: local.repo.com/nginx-vts:latest
    restart: always
    environment:
      - TZ=${DOCKER_TZ}
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - ${MY_DOCKER_DATA_DIR}/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-logs:/var/log/nginx
      - ${MY_DOCKER_DATA_DIR}/nginx/auth/.htpasswd:/etc/nginx/.htpasswd
      - ${MY_DOCKER_DATA_DIR}/nginx/geo/GeoIPCity.dat:/usr/share/GeoIP/GeoCity.dat
      - ${MY_DOCKER_DATA_DIR}/nginx/geo/GeoIP.dat:/usr/share/GeoIP/GeoIP.dat
    ports:
      - 80:80
      - 443:443
    networks:
      frontend:
        aliases:
          - nginx-vts-status  

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    restart: always
    environment:
      - TZ=${DOCKER_TZ}
    depends_on:
      - simple-apache-php
      - portainer
      - cadvisor
      - nginx-redirect
      - grav
      - myregistry
      - grafana
      - prometheus
      - nginx
      - nextcloud-web
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 30s:60s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]
    networks:
      - frontend
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - ${MY_DOCKER_DATA_DIR}/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${MY_DOCKER_DATA_DIR}/nginx-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-ssl:
    container_name: nginx-ssl
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx-gen
    environment:
      - TZ=${DOCKER_TZ}
      - NGINX_PROXY_CONTAINER=nginx
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      #- ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
      #- DEBUG=true
    networks:
      - frontend
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - ${MY_DOCKER_DATA_DIR}/nginx/vhost.d:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    container_name: portainer
    image: portainer/portainer
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${PORTAINER_DOMAIN}
      - VIRTUAL_PORT=9000
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${PORTAINER_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

  # Cadvisor should not be exposed openly externally because it has no auth-mechanism
  # Use predefined nginx vhost setting and create an auth-file for basic auth. See readme.
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: 'cadvisor'
    restart: always
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${CADVISOR_DOMAIN}
      - VIRTUAL_PORT=8080
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${CADVISOR_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    networks:
      - frontend
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  openvpn-server:
    privileged: true
    image: kylemanna/openvpn
    container_name: openvpn-server
    environment:
      - TZ=${DOCKER_TZ}
    ports:
      - "1194:1194/udp"
    # TCP when UDP doesn't work...
    #  - "443:443/tcp"
    restart: always
    volumes:
     - ${MY_DOCKER_DATA_DIR}/openvpn-server/config:/etc/openvpn

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    networks:
      - backend
    environment:
      - CLEANUP=true
      # In CI/CD environment, use interval in seconds for continuous builds
      #- INTERVAL=30
      - CRON="0 2 * * *"
      - SELF_UPDATE=true
      #- IGNORE=mongo influxdb postgres mariadb
      - TZ=${DOCKER_TZ}
      - NOTIFIERS="mailtos://${GMAIL_USERNAME}:${GMAIL_PASSWORD}@gmail.com?to=${NOTIFICATION_EMAIL}"
    command: --data-export prometheus --prometheus-addr 0.0.0.0
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/root/.docker/config.json

  myregistry:
    container_name: myregistry
    image: registry:2
    networks:
      - frontend
    expose:
      - "5000"
    restart: always
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${REGISTRY_DOMAIN}
      - VIRTUAL_PORT=5000
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${REGISTRY_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Docker registry access
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/.htpasswd
    volumes:
      - ${MY_DOCKER_DATA_DIR}/registry/data:/var/lib/registry
      - nginx-certs:/certs
      - ${MY_DOCKER_DATA_DIR}/registry/auth:/auth

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    networks:
      - frontend
      - backend
    expose:
      - "9090"
    environment:
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=${PROMETHEUS_DOMAIN}
      - VIRTUAL_PORT=9090
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${PROMETHEUS_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    volumes:
      - ${MY_DOCKER_DATA_DIR}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${MY_DOCKER_DATA_DIR}/prometheus/alert.rules:/etc/prometheus/alert.rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  prometheus-alertmanager:
    container_name: prometheus-alertmanager
    image: prom/alertmanager:latest
    restart: always
    environment:
      - TZ=${DOCKER_TZ}
    networks:
      - backend
    #expose:
    #  - "9093"
    volumes:
      - ${MY_DOCKER_DATA_DIR}/prometheus/alertmanager.yml:/alertmanager.yml
    command:
      - '--config.file=/alertmanager.yml'

  nginx-vts-exporter:
    container_name: nginx-vts-exporter
    image: sophos/nginx-vts-exporter
    restart: always
    networks:
      - backend
      - frontend
    environment:
      - TZ=${DOCKER_TZ}
      - NGINX_STATUS=http://nginx-vts-status/status/format/json

  nextcloud-vts-exporter:
    container_name: nextcloud-vts-exporter
    image: sophos/nginx-vts-exporter
    restart: always
    networks:
      - backend
      - frontend
    environment:
      - TZ=${DOCKER_TZ}
      - NGINX_STATUS=http://nextcloud-vts-status/status/format/json

  nextcloud-prometheus-exporter:
    container_name: nextcloud-prometheus-exporter
    build: ./nextcloud-prometheus-exporter/.
    #image: local.repo.com/nextcloud-prometheus-exporter:latest
    restart: always
    networks:
      - backend
    environment:
      - TZ=${DOCKER_TZ}
      - NEXTCLOUD_SERVERINFO_URL=https://${NEXTCLOUD_DOMAIN}/ocs/v2.php/apps/serverinfo/api/v1/info
      - NEXTCLOUD_USERNAME=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - prometheus
    networks:
      - backend
      - frontend
    expose:
      - "3000"
    environment:
      - TZ=${DOCKER_TZ}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - VIRTUAL_HOST=${GRAFANA_DOMAIN}
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=${GRAFANA_DOMAIN}
      - LETSENCRYPT_EMAIL=${NOTIFICATION_EMAIL}
    volumes:
      - grafana_data:/var/lib/grafana

  smtp-relay:
    container_name: smtp-relay
    build: ./smtp-relay/.
    #image: local.repo.com/smtp-relay:latest
    restart: always
    networks: 
      - backend
    environment:
      - TZ=${DOCKER_TZ}
      - RELAY_HOST=smtp.gmail.com
      - RELAY_PORT=587
      - RELAY_USERNAME=${GMAIL_USERNAME}@gmail.com
      - RELAY_PASSWORD=${GMAIL_PASSWORD}
